### ISSUE TITLE
(Horrible) Markdown Previewer

### ISSUE THREAD

**Issue by BumpyBill** [CodingTrain/LateNight#5]
**(Sorry If I'm Not Allowed To Create An Issue)**

G'day! I made a (horrible) markdown previewer for Dan's late-night streams that automatically updates when the file is pushed. If you would like to make the site look prettier you can create a pull request.

The Site: https://latenight-md.herokuapp.com/
The Repository: https://github.com/Lachie-Source/latenight-md 

Edit: I made it because I was bored (if you wondering)

**Comment by simon-tiger** [comment]
@Lachie-Source Not allowed to create an issue!? The Coding Train is open-minded and undiscriminating. *Everyone* is allowed to do stuff for the community, as long as it is not harassing.
